import {
  Brain,
  MessageCircle,
  Users,
  Cpu,
  Lightbulb,
  Landmark,
  Atom,
  Leaf,
  FlaskConical,
  BookOpen,
  Globe2,
  MapPin,
  ScrollText,
  Heart,
  Code,
  Bot,
  BookMarked,
  Coins,
  Scale,
} from 'lucide-react';
import { Category } from "../models";

export const menuItems = [
  { label: 'Materias', id: 'materias' },
  { label: 'Servicios', id: 'servicios' },
  { label: 'Precios', id: 'precios' },
  { label: 'Contacto', id: 'contacto' },
];
export const waMessage = "https://wa.me/573124184842?text=Hola%20Semillas%20del%20Saber%2C%20necesito%20ayuda%20con%20mis%20tareas.";
export const subjectCategories: Category[] = [
  {
    id: 'logico',
    name: 'Ciencias del Pensamiento Lógico',
    icon: Brain,
    gradient: 'from-blue-500 to-indigo-600',
    bgLight: 'bg-blue-50',
    iconBg: 'bg-blue-100',
    borderColor: 'border-blue-200 hover:border-blue-400',
    tagline: 'Razonamiento, análisis y resolución de problemas',
    subjects: [
      { name: 'Matemáticas', icon: Atom },
      { name: 'Ciencias Naturales & Educación Ambiental', icon: Leaf },
      { name: 'Química', icon: FlaskConical },
    ],
  },
  {
    id: 'comunicacion',
    name: 'Comunicación y Expresión',
    icon: MessageCircle,
    gradient: 'from-pink-500 to-rose-600',
    bgLight: 'bg-pink-50',
    iconBg: 'bg-pink-100',
    borderColor: 'border-pink-200 hover:border-pink-400',
    tagline: 'Domina el lenguaje y conecta con el mundo',
    subjects: [
      { name: 'Lengua Castellana', icon: BookOpen },
      { name: 'Idioma Extranjero — Inglés', icon: Globe2 },
    ],
  },
  {
    id: 'sociedad',
    name: 'Sociedad y Ciudadanía',
    icon: Users,
    gradient: 'from-emerald-500 to-teal-600',
    bgLight: 'bg-emerald-50',
    iconBg: 'bg-emerald-100',
    borderColor: 'border-emerald-200 hover:border-emerald-400',
    tagline: 'Comprende tu entorno social e histórico',
    subjects: [
      { name: 'Historia', icon: ScrollText },
      { name: 'Geografía', icon: MapPin },
      { name: 'Constitución Política', icon: Landmark },
      { name: 'Educación en Ética y Valores', icon: Heart },
    ],
  },
  {
    id: 'tecnologia',
    name: 'Tecnología',
    icon: Cpu,
    gradient: 'from-amber-500 to-orange-600',
    bgLight: 'bg-amber-50',
    iconBg: 'bg-amber-100',
    borderColor: 'border-amber-200 hover:border-amber-400',
    tagline: 'Crea, programa e innova con tecnología',
    subjects: [
      { name: 'Programación', icon: Code },
      { name: 'Robótica', icon: Bot },
    ],
  },
  {
    id: 'critica',
    name: 'Crítico-Reflexiva',
    icon: Lightbulb,
    gradient: 'from-purple-500 to-violet-600',
    bgLight: 'bg-purple-50',
    iconBg: 'bg-purple-100',
    borderColor: 'border-purple-200 hover:border-purple-400',
    tagline: 'Piensa, cuestiona y transforma ideas',
    subjects: [{ name: 'Filosofía', icon: BookMarked }],
  },
  {
    id: 'economicas',
    name: 'Ciencias Económicas y Políticas',
    icon: Landmark,
    gradient: 'from-cyan-500 to-sky-600',
    bgLight: 'bg-cyan-50',
    iconBg: 'bg-cyan-100',
    borderColor: 'border-cyan-200 hover:border-cyan-400',
    tagline: 'Entiende cómo funcionan la economía y la política',
    subjects: [
      { name: 'Economía', icon: Coins },
      { name: 'Política', icon: Scale },
    ],
  },
];